version: '3'

services: 
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on: 
      - "zookeeper"
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-10.11.1.111}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "asw.kafka.channel.alpha:4:1,asw.kafka.channel.beta:4:1,asw.kafka.channel.gamma:4:1"      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  eureka:
    build: 
      context: ./eureka-server
    depends_on: 
      - "kafka"
    ports:
      - "8761:8761"
    container_name: eureka
  servizioa:
    depends_on: 
      - "kafka"
      - "zookeeper"
    build: './servizioA' 
  serviziob:
    depends_on:
      - "kafka"
      - "zookeeper"
    build: './servizioB'