# application.yml 
--- 
spring: 
  application: 
    name: aservice

#kafka: IN APPLICATION PROPERTIES
#  producer:
#    bootstrap: kafka:9092                                 #DA MODIFICARE IN DOCKER POTREI USARE {DOCKER_HOST_IP}
#    bootstrap: localhost:9092
    #    group: WorkUnitApp
#    topic: canalezeta 
#  channel:
#    out: asw.kafka.channel.canalezeta

eureka: 
  client: 
    serviceUrl: 
      #defaultZone: http://localhost:8761/eureka/       #LOCAL
      defaultZone: http://eureka:8761/eureka               
  instance:                                                   # questo rappresenta la SINGOLA ISTANZA del servizio
    leaseRenewalIntervalInSeconds: 10                         # DO NOT DO THIS IN PRODUCTION
    #leaseExpirationDurationInSeconds: 5                      #SERVE?
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}  #DA MODIFICARE IN NOMI DI PERSONA

server:
  port: ${PORT:${SERVER_PORT:0}}
  #port: 8080

names: Achille, Alen, Alex, Alice
animals: Balena, Cammello, Elefante, Pinguino, Volpe

#channelout: cft.kafka.channel.canalezeta

#---                                                           #SERVE?

#spring: 
#  profiles: istanzauno
#  application: 
#     name: nomeservizio
    
#animals: Balena, Cammello, Elefante, Pinguino, Volpe

