# application.yml 
--- 
spring: 
  application: 
    name: servizioA                                           #SERVE?

#kafka:
#  producer:
#    bootstrap: localhost:9092
#    topic: canalezeta 

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka:8761/eureka/                #QUESTA PER DOPO
  instance:                                                   # questo rappresenta la SINGOLA ISTANZA del servizio
    leaseRenewalIntervalInSeconds: 10                         # DO NOT DO THIS IN PRODUCTION
    #leaseExpirationDurationInSeconds: 5                      #SERVE?
    metadataMap: 
      instanceId: ${spring.application.name}:${server.port}  #DA MODIFICARE IN NOMI DI PERSONA

server: 
  port: 8080

animals: Elefante, Balena, Pinguino, Cammello

#---

#spring: 
#  profiles: istanzauno
#  application: 
#     name: nomeservizio
    
#animals: Elefante, Balena, Pinguino, Cammello
