# application.yml 
--- 
spring: 
  application: 
    name: servizioB

#kafka:   IN APPLICATION PROPERTIES
#  consumer:
#    bootstrap: kafka:9092
#    bootstrap: localhost:9092
#    group: WorkUnitApp
#    topic: canalezeta
#  channel:
#    in: asw.kafka.channel.canalezeta
#  groupId: servizioBConsumer

eureka: 
  client: 
    serviceUrl:
      defaultZone: http://eureka:8761/eureka 
      #defaultZone: http://localhost:8761/eureka/
  instance:                                                   # questo rappresenta la SINGOLA ISTANZA del servizio
    leaseRenewalIntervalInSeconds: 10                         # DO NOT DO THIS IN PRODUCTION
    #leaseExpirationDurationInSeconds: 5                      #SERVE?
    metadataMap: 
      instanceId: ${spring.application.name}:${server.port}  #DA MODIFICARE IN NOMI DI PERSONA

      
server: 
  port: 8081