# application.yml 
--- 
spring: 
  application: 
    name: bservice

#kafka:   IN APPLICATION PROPERTIES
#  consumer:
#    bootstrap: kafka:9092
#    bootstrap: localhost:9092
#    group: WorkUnitApp
#    topic: canalezeta
#  channel:
#    in: asw.kafka.channel.canalezeta
#  groupId: servizioBConsumer

eureka: 
  client: 
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/     #LOCALE
      defaultZone: http://eureka:8761/eureka 
  instance:                                                   # questo rappresenta la SINGOLA ISTANZA del servizio
    leaseRenewalIntervalInSeconds: 10                         # DO NOT DO THIS IN PRODUCTION
    #leaseExpirationDurationInSeconds: 5                      #SERVE?
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}  #DA MODIFICARE IN NOMI DI PERSONA

      
server:
  port: ${PORT:${SERVER_PORT:0}}
  #port: 8080

names: Beatrice, Beararda, Bernardo
animals: Balena, Cammello, Elefante, Pinguino, Volpe

#channelin: cft.kafka.channel.canalezeta
#groupid: simple-consumer