# application.yml 
--- 
spring: 
  application: 
    name: cservice

eureka: 
  client: 
    serviceUrl: 
      #defaultZone: http://localhost:8761/eureka/       #LOCALE
      defaultZone: http://eureka:8761/eureka/                
  instance:                                                   # questo rappresenta la SINGOLA ISTANZA del servizio
    leaseRenewalIntervalInSeconds: 10                         # DO NOT DO THIS IN PRODUCTION
    #leaseExpirationDurationInSeconds: 5                      #SERVE?
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}  #DA MODIFICARE IN NOMI DI PERSONA

server: 
  port: ${PORT:${SERVER_PORT:0}}
  
names: Calogero ,Carlo, Carmen, Carmela, Ciro
#---                                                           #SERVE?

#spring: 
#  profiles: istanzauno
#  application: 
#     name: nomeservizio
    
#animals: Balena, Cammello, Elefante, Pinguino, Volpe

